Repository I2PC/xmipp3-installer, pull requests merged in 2025-03, with the labels that each got.

#75 CMake modes do not send installation info by default
  src/xmipp3_installer/installer/modes/mode_cmake/mode_cmake_executor.py
  tests/unitary/installer/modes/mode_cmake/mode_cmake_executor_test.py
Labels: bug

#77 E2E test for `configBuild` mode
  poetry.lock
  pyproject.toml
  tests/e2e/__init__.py
  tests/e2e/mode_config_build_test.py
  tests/e2e/shell_command_outputs/mode_config_build.py
  tests/test_files/cmake-cases/config_error/CMakeLists.txt
  tests/test_files/cmake-cases/install_error/CMakeLists.txt
  tests/test_files/cmake-cases/valid/CMakeLists.txt
Labels: tests

#84 Fix release commands
  .github/workflows/release.yml
Labels: bug

#88 Improved project metadata
  LICENSE.txt
  README.md
  pyproject.toml
Labels: enhancement

#92 Better installation docs
  README.md
Labels: documentation

#96 Increase timeout
  src/xmipp3_installer/api_client/api_client.py
  tests/unitary/api_client/api_client_test.py
Labels: bug, enhancement

#97 Fix path to data tests
  src/xmipp3_installer/installer/modes/mode_sync/mode_test_executor.py
Labels: bug

#106 Disable build tests by default
  src/xmipp3_installer/repository/config.py
  src/xmipp3_installer/repository/config_vars/default_values.py
  tests/integration/repository/config/file_content.py
  tests/test_files/conf-files/input/default.conf
  tests/test_files/conf-files/output/default.conf
  tests/test_files/conf-files/output/unknown.conf
  tests/unitary/repository/config_test.py
Labels: enhancement

#104 spelling corrections
  src/xmipp3_installer/application/cli/arguments/modes.py
  src/xmipp3_installer/application/cli/arguments/params.py
  tests/integration/application/cli/mode_messages/mode_add_model.py
Labels: enhancement
